Django/lecture3/hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet"),
    path("brian", views.brian, name="brian"),
    path("david", views.david, name="david")
]

Django/lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
]

Django/lecture3/newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index")
]

Django/lecture3/tasks/urls.py
from django.urls import path

from . import views


app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

Django/lecture3/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    #return HttpResponse("Hello, Django!!!!")
    return render(request, "hello/index.html")
    
def brian(request):
    return HttpResponse("Hello, Sheena")
    
def david(request):
    return HttpResponse("What a great day, David.")
    
def greet(request, name):
    #return HttpResponse(f"Hello, {name}!")
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

Django/lecture3/newyear/views.py
import datetime


from django.shortcuts import render

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

Django/lecture3/tasks/views.py
from django.shortcuts import render


tasks = ["foo", "bar", "baz"]


# Create your views here.
def index(request):
    return render(request, "tasks/index.html", {
        "tasks": tasks
    })
    
def add(request):
    return render(request, "tasks/add.html")

Django/lecture3/hello/templates/greet.html
<!DOCTYPE html>
<html lang="" en">
<head>
    <title>Hello!</title>
</head>
<body>
    <h1>Hello, {{name}}!!!!!</h1>
</body>
</html>

Django/lecture3/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang=""en">
    <head>
        <title>Hello!</title>
    </head>
    <body>
        <h1>Hello, world!!!!!</h1>
    </body>
</html>

Django/lecture3/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="" en">
<head>
    <title>Is it New Year's?</title>
    <link href="{% static 'newyear/styles.css' %}" rel="stylesheet" />
</head>
<body>
    {% if newyear %}
        <h1>YES</h1>
    {%  else %}
        <h1>NO</h1>
    {% endif %}

</body>
</html>

Django/lecture3/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Add Task</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        <input type="text" name="task" />
        <input type="submit" />
    </form>
    <a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

Django/lecture3/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Tasks</h1>
    <ul>
        {% for task in tasks %}
            <li>{{task}}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add a New Task</a>
{% endblock %}

Django/lecture3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="" en">
<head>
    <title>Tasks</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>